<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}" class="scroll-smooth">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="theme-color" content="#FAFAFA">
    <title>Impact Report | {{ $report->title ?? 'Campaign' }}</title>
    
    <!-- Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Cormorant+Garamond:ital,wght@0,400;0,600;1,400&family=Inter:wght@300;400;500;600&display=swap" rel="stylesheet">
    
    <!-- Styles -->
    @vite(['resources/css/app.css', 'resources/js/app.js'])
    
    <style>
        :root {
            --color-ink: #111111;
            --color-paper: #FAFAFA;
            --color-accent: #B45309; /* Deep amber */
            --color-muted: #737373;
        }
        body {
            font-family: 'Inter', sans-serif;
            background-color: var(--color-paper);
            color: var(--color-ink);
            line-height: 1.6;
        }
        h1, h2, h3, .serif-font {
            font-family: 'Cormorant Garamond', serif;
        }
        
        /* Editorial Minimalist Styles */
        .editorial-header {
            border-bottom: 2px solid var(--color-ink);
            padding-bottom: 2rem;
            margin-bottom: 3rem;
        }
        .stat-block {
            border-left: 1px solid var(--color-ink);
            padding-left: 1.5rem;
        }
        .stat-value {
            font-size: 4rem;
            line-height: 1;
            font-weight: 400;
            letter-spacing: -0.02em;
        }
        .stat-label {
            font-size: 0.875rem;
            text-transform: uppercase;
            letter-spacing: 0.05em;
            color: var(--color-muted);
            margin-top: 0.5rem;
            display: block;
        }
        .map-container {
            filter: grayscale(100%) contrast(120%);
            transition: filter 0.5s ease;
        }
        .map-container:hover {
            filter: grayscale(0%) contrast(100%);
        }
        .btn-outline {
            border: 1px solid var(--color-ink);
            padding: 0.75rem 1.5rem;
            text-transform: uppercase;
            font-size: 0.75rem;
            letter-spacing: 0.1em;
            font-weight: 600;
            transition: all 0.3s ease;
        }
        .btn-outline:hover {
            background-color: var(--color-ink);
            color: var(--color-paper);
        }
        .btn-outline:focus-visible {
            outline: 2px solid var(--color-accent);
            outline-offset: 4px;
        }
    </style>
</head>
<body class="antialiased min-h-screen">

    <main class="w-full max-w-5xl mx-auto px-6 py-16 md:py-24">
        
        <!-- Navigation -->
        <nav class="mb-16 flex justify-between items-center" aria-label="Breadcrumb">
            <a href="{{ route('campaigns.show', $report->campaign->slug ?? '#') }}" class="text-sm font-medium hover:text-[var(--color-accent)] transition-colors inline-flex items-center gap-2 focus-visible:outline-offset-4 focus-visible:outline-[var(--color-accent)]">
                &larr; Back to Campaign
            </a>
            <div class="text-xs uppercase tracking-widest text-[var(--color-muted)] font-semibold">
                Official Impact Report
            </div>
        </nav>

        <!-- Header -->
        <header class="editorial-header">
            <h1 class="text-5xl md:text-7xl font-semibold tracking-tight mb-6">{{ $report->title ?? 'Water for Tomorrow' }}</h1>
            <div class="flex flex-col md:flex-row md:items-end justify-between gap-6">
                <p class="text-xl md:text-2xl text-[var(--color-muted)] max-w-2xl serif-font italic">
                    {{ $report->summary ?? 'A comprehensive overview of the impact generated by our community in the targeted regions.' }}
                </p>
                <div class="text-sm font-medium">
                    Published: <time datetime="{{ $report->published_at ?? now() }}">{{ \Carbon\Carbon::parse($report->published_at ?? now())->format('F d, Y') }}</time>
                </div>
            </div>
        </header>

        <!-- Key Stats Grid -->
        <section class="grid grid-cols-1 md:grid-cols-3 gap-12 mb-24" aria-labelledby="stats-heading">
            <h2 id="stats-heading" class="sr-only">Key Impact Statistics</h2>
            
            <div class="stat-block">
                <div class="stat-value serif-font text-[var(--color-accent)]">{{ $report->beneficiaries_count ?? '12,450' }}</div>
                <span class="stat-label">Direct Beneficiaries</span>
            </div>
            
            <div class="stat-block">
                <div class="stat-value serif-font">{{ $report->funds_deployed ?? '$240k' }}</div>
                <span class="stat-label">Funds Deployed</span>
            </div>
            
            <div class="stat-block">
                <div class="stat-value serif-font">{{ $report->projects_completed ?? '18' }}</div>
                <span class="stat-label">Projects Completed</span>
            </div>
        </section>

        <!-- Story / Content -->
        <article class="prose prose-lg prose-slate max-w-none mb-24">
            <h2 class="text-3xl serif-font mb-6">The Outcome</h2>
            <div class="columns-1 md:columns-2 gap-12 text-justify">
                {!! $report->content ?? '<p>Through the incredible generosity of our donors and the tireless efforts of our volunteers, we have successfully implemented sustainable solutions in the target regions. This report details the specific allocations, execution phases, and the long-term maintenance strategy established with local leaders.</p><p>Transparency is our core principle. Every dollar accounted for has directly contributed to the infrastructure and training programs required to ensure lasting change. Read on to explore the geographical impact and view direct evidence from the field.</p>' !!}
            </div>
        </article>

        <!-- Map Section -->
        <section class="mb-24" aria-labelledby="map-heading">
            <div class="flex justify-between items-end mb-8">
                <h2 id="map-heading" class="text-3xl serif-font">Geographical Reach</h2>
                <span class="text-sm uppercase tracking-widest text-[var(--color-muted)]">Verified Locations</span>
            </div>
            <!-- Google Maps Placeholder / Integration -->
            <div class="w-full h-[500px] bg-slate-200 map-container relative overflow-hidden" aria-hidden="true">
                <iframe 
                    width="100%" 
                    height="100%" 
                    style="border:0;" 
                    loading="lazy" 
                    allowfullscreen 
                    src="https://www.google.com/maps/embed/v1/place?key={{ config('services.google_maps.key') }}&q=Nairobi,Kenya"
                    title="Interactive map showing beneficiary locations">
                </iframe>
                @if(!config('services.google_maps.key'))
                    <div class="absolute inset-0 flex items-center justify-center bg-slate-100 border border-slate-300">
                        <p class="text-sm font-medium text-slate-500 uppercase tracking-widest">Map API Key Required</p>
                    </div>
                @endif
            </div>
        </section>

        <!-- Footer Actions -->
        <footer class="border-t border-[var(--color-ink)] pt-12 flex flex-col sm:flex-row justify-between items-center gap-6">
            <div>
                <h3 class="font-semibold text-lg">Want to keep a copy?</h3>
                <p class="text-sm text-[var(--color-muted)]">Download the cryptographically verifiable PDF report.</p>
            </div>
            <a href="{{ route('impact.download', $report->id ?? 1) }}" class="btn-outline inline-flex items-center gap-2">
                <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-4l-4 4m0 0l-4-4m4 4V4"></path></svg>
                Download PDF
            </a>
        </footer>

    </main>

</body>
</html>
